services:
  web_app:
    container_name: web_app
    depends_on:
      - back_end
    build:
      context: ./web_app
    env_file:
      - web_app/.env
    ports:
      - "80:3000"
    networks:
      - my-net

  back_end:
    container_name: back_end
    build:
      context: ./back_end
    env_file:
      - back_end/.env
    ports:
      - "8080:8080"
    networks:
      - my-net
    restart: always

networks:
  my-net:
    driver: bridge
